### ISSUE TITLE
Transfer fees not shown in Mobile Wallet

### ISSUE THREAD

**Issue by Marky-N** [oxen-io/oxen-mobile-wallet#14]
On the mobile wallet the transfer fee doesn't show, which should be shown. Here is also an example how staking is shown, also no transfer fees shown.

Staking is shown as follows:
![20210914_095638000_iOS](https://user-images.githubusercontent.com/77722427/133377325-203e5934-0972-4785-8051-267b53a2962d.png)

And when looking at the details, the fee is missing:
![20210914_095646000_iOS](https://user-images.githubusercontent.com/77722427/133377328-23659509-4cfe-414c-8e55-15c757c0d795.jpg)

How the the staking and fee details are shown on Desktop Wallet:
![20210914_072118230_iOS](https://user-images.githubusercontent.com/77722427/133376973-ab503719-ceb0-4acc-a097-1dc281066fb8.jpg)

**Comment by jagerman** [comment]
This was fixed in the 1.0.9 release.
